import 'package:equatable/equatable.dart';

class CountryModel {
  CountryModel({
    required this.name,
    required this.code,
    required this.dialCode,
  });

  factory CountryModel.fromJson(Map<String, dynamic> json) {
    return CountryModel(
      name: json['name'] as String,
      code: json['code'] as String,
      dialCode: json['dialCode'] as String,
    );
  }

  final String name;
  final String code;
  final String dialCode;

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'code': code,
      'dialCode': dialCode,
    };
  }
}

class CountryPresetModel extends Equatable {
  const CountryPresetModel({
    this.createdAt,
    this.updatedAt,
    required this.id,
    required this.name,
    required this.flag,
  });

  factory CountryPresetModel.fromJson(Map<String, dynamic> json) {
    return CountryPresetModel(
      createdAt: json['createdAt'] == null ? null : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null ? null : DateTime.parse(json['updatedAt'] as String),
      id: json['id'] as String,
      name: json['name'] as String,
      flag: json['flag'] as String,
    );
  }
  static const empty = CountryPresetModel(
    id: '',
    name: '',
    flag: '',
    createdAt: null,
    updatedAt: null,
  );

  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String id;
  final String name;
  final String flag;

  Map<String, dynamic> toJson() {
    return {
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'id': id,
      'name': name,
      'flag': flag,
    };
  }

  @override
  List<Object?> get props => [createdAt, updatedAt, id, name, flag];
}

class Countries {
  static List<CountryModel> all = [
    CountryModel(name: 'Afghanistan', code: 'AF', dialCode: '+93'),
    CountryModel(name: 'Albania', code: 'AL', dialCode: '+355'),
    CountryModel(name: 'Algeria', code: 'DZ', dialCode: '+213'),
    CountryModel(name: 'American Samoa', code: 'AS', dialCode: '+1684'),
    CountryModel(name: 'Andorra', code: 'AD', dialCode: '+376'),
    CountryModel(name: 'Angola', code: 'AO', dialCode: '+244'),
    CountryModel(name: 'Anguilla', code: 'AI', dialCode: '+1264'),
    CountryModel(name: 'Antarctica', code: 'AQ', dialCode: '+672'),
    CountryModel(name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1268'),
    CountryModel(name: 'Argentina', code: 'AR', dialCode: '+54'),
    CountryModel(name: 'Armenia', code: 'AM', dialCode: '+374'),
    CountryModel(name: 'Aruba', code: 'AW', dialCode: '+297'),
    CountryModel(name: 'Australia', code: 'AU', dialCode: '+61'),
    CountryModel(name: 'Austria', code: 'AT', dialCode: '+43'),
    CountryModel(name: 'Azerbaijan', code: 'AZ', dialCode: '+994'),
    CountryModel(name: 'Bahamas', code: 'BS', dialCode: '+1242'),
    CountryModel(name: 'Bahrain', code: 'BH', dialCode: '+973'),
    CountryModel(name: 'Bangladesh', code: 'BD', dialCode: '+880'),
    CountryModel(name: 'Barbados', code: 'BB', dialCode: '+1246'),
    CountryModel(name: 'Belarus', code: 'BY', dialCode: '+375'),
    CountryModel(name: 'Belgium', code: 'BE', dialCode: '+32'),
    CountryModel(name: 'Belize', code: 'BZ', dialCode: '+501'),
    CountryModel(name: 'Benin', code: 'BJ', dialCode: '+229'),
    CountryModel(name: 'Bermuda', code: 'BM', dialCode: '+1441'),
    CountryModel(name: 'Bhutan', code: 'BT', dialCode: '+975'),
    CountryModel(name: 'Bolivia', code: 'BO', dialCode: '+591'),
    CountryModel(name: 'Bosnia and Herzegovina', code: 'BA', dialCode: '+387'),
    CountryModel(name: 'Botswana', code: 'BW', dialCode: '+267'),
    CountryModel(name: 'Brazil', code: 'BR', dialCode: '+55'),
    CountryModel(name: 'British Indian Ocean Territory', code: 'IO', dialCode: '+246'),
    CountryModel(name: 'Brunei Darussalam', code: 'BN', dialCode: '+673'),
    CountryModel(name: 'Bulgaria', code: 'BG', dialCode: '+359'),
    CountryModel(name: 'Burkina Faso', code: 'BF', dialCode: '+226'),
    CountryModel(name: 'Burundi', code: 'BI', dialCode: '+257'),
    CountryModel(name: 'Cambodia', code: 'KH', dialCode: '+855'),
    CountryModel(name: 'Cameroon', code: 'CM', dialCode: '+237'),
    CountryModel(name: 'Canada', code: 'CA', dialCode: '+1'),
    CountryModel(name: 'Cape Verde', code: 'CV', dialCode: '+238'),
    CountryModel(name: 'Cayman Islands', code: 'KY', dialCode: '+1345'),
    CountryModel(name: 'Central African Republic', code: 'CF', dialCode: '+236'),
    CountryModel(name: 'Chad', code: 'TD', dialCode: '+235'),
    CountryModel(name: 'Chile', code: 'CL', dialCode: '+56'),
    CountryModel(name: 'China', code: 'CN', dialCode: '+86'),
    CountryModel(name: 'Christmas Island', code: 'CX', dialCode: '+61'),
    CountryModel(name: 'Cocos (Keeling) Islands', code: 'CC', dialCode: '+61'),
    CountryModel(name: 'Colombia', code: 'CO', dialCode: '+57'),
    CountryModel(name: 'Comoros', code: 'KM', dialCode: '+269'),
    CountryModel(name: 'Congo', code: 'CG', dialCode: '+242'),
    CountryModel(name: 'Cook Islands', code: 'CK', dialCode: '+682'),
    CountryModel(name: 'Costa Rica', code: 'CR', dialCode: '+506'),
    CountryModel(name: 'Croatia', code: 'HR', dialCode: '+385'),
    CountryModel(name: 'Cuba', code: 'CU', dialCode: '+53'),
    CountryModel(name: 'Cyprus', code: 'CY', dialCode: '+357'),
    CountryModel(name: 'Czech Republic', code: 'CZ', dialCode: '+420'),
    CountryModel(name: 'Denmark', code: 'DK', dialCode: '+45'),
    CountryModel(name: 'Djibouti', code: 'DJ', dialCode: '+253'),
    CountryModel(name: 'Dominica', code: 'DM', dialCode: '+1767'),
    CountryModel(name: 'Dominican Republic', code: 'DO', dialCode: '+1849'),
    CountryModel(name: 'Ecuador', code: 'EC', dialCode: '+593'),
    CountryModel(name: 'Egypt', code: 'EG', dialCode: '+20'),
    CountryModel(name: 'El Salvador', code: 'SV', dialCode: '+503'),
    CountryModel(name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240'),
    CountryModel(name: 'Eritrea', code: 'ER', dialCode: '+291'),
    CountryModel(name: 'Estonia', code: 'EE', dialCode: '+372'),
    CountryModel(name: 'Ethiopia', code: 'ET', dialCode: '+251'),
    CountryModel(name: 'Falkland Islands', code: 'FK', dialCode: '+500'),
    CountryModel(name: 'Faroe Islands', code: 'FO', dialCode: '+298'),
    CountryModel(name: 'Fiji', code: 'FJ', dialCode: '+679'),
    CountryModel(name: 'Finland', code: 'FI', dialCode: '+358'),
    CountryModel(name: 'France', code: 'FR', dialCode: '+33'),
    CountryModel(name: 'French Guiana', code: 'GF', dialCode: '+594'),
    CountryModel(name: 'French Polynesia', code: 'PF', dialCode: '+689'),
    CountryModel(name: 'Gabon', code: 'GA', dialCode: '+241'),
    CountryModel(name: 'Gambia', code: 'GM', dialCode: '+220'),
    CountryModel(name: 'Georgia', code: 'GE', dialCode: '+995'),
    CountryModel(name: 'Germany', code: 'DE', dialCode: '+49'),
    CountryModel(name: 'Ghana', code: 'GH', dialCode: '+233'),
    CountryModel(name: 'Gibraltar', code: 'GI', dialCode: '+350'),
    CountryModel(name: 'Greece', code: 'GR', dialCode: '+30'),
    CountryModel(name: 'Greenland', code: 'GL', dialCode: '+299'),
    CountryModel(name: 'Grenada', code: 'GD', dialCode: '+1473'),
    CountryModel(name: 'Guadeloupe', code: 'GP', dialCode: '+590'),
    CountryModel(name: 'Guam', code: 'GU', dialCode: '+1671'),
    CountryModel(name: 'Guatemala', code: 'GT', dialCode: '+502'),
    CountryModel(name: 'Guernsey', code: 'GG', dialCode: '+44'),
    CountryModel(name: 'Guinea', code: 'GN', dialCode: '+224'),
    CountryModel(name: 'Guinea-Bissau', code: 'GW', dialCode: '+245'),
    CountryModel(name: 'Guyana', code: 'GY', dialCode: '+592'),
    CountryModel(name: 'Haiti', code: 'HT', dialCode: '+509'),
    CountryModel(name: 'Honduras', code: 'HN', dialCode: '+504'),
    CountryModel(name: 'Hong Kong', code: 'HK', dialCode: '+852'),
    CountryModel(name: 'Hungary', code: 'HU', dialCode: '+36'),
    CountryModel(name: 'Iceland', code: 'IS', dialCode: '+354'),
    CountryModel(name: 'India', code: 'IN', dialCode: '+91'),
    CountryModel(name: 'Indonesia', code: 'ID', dialCode: '+62'),
    CountryModel(name: 'Iran', code: 'IR', dialCode: '+98'),
    CountryModel(name: 'Iraq', code: 'IQ', dialCode: '+964'),
    CountryModel(name: 'Ireland', code: 'IE', dialCode: '+353'),
    CountryModel(name: 'Isle of Man', code: 'IM', dialCode: '+44'),
    CountryModel(name: 'Italy', code: 'IT', dialCode: '+39'),
    CountryModel(name: 'Jamaica', code: 'JM', dialCode: '+1876'),
    CountryModel(name: 'Japan', code: 'JP', dialCode: '+81'),
    CountryModel(name: 'Jersey', code: 'JE', dialCode: '+44'),
    CountryModel(name: 'Jordan', code: 'JO', dialCode: '+962'),
    CountryModel(name: 'Kazakhstan', code: 'KZ', dialCode: '+7'),
    CountryModel(name: 'Kenya', code: 'KE', dialCode: '+254'),
    CountryModel(name: 'Kiribati', code: 'KI', dialCode: '+686'),
    CountryModel(name: 'Kuwait', code: 'KW', dialCode: '+965'),
    CountryModel(name: 'Kyrgyzstan', code: 'KG', dialCode: '+996'),
    CountryModel(name: 'Laos', code: 'LA', dialCode: '+856'),
    CountryModel(name: 'Latvia', code: 'LV', dialCode: '+371'),
    CountryModel(name: 'Lebanon', code: 'LB', dialCode: '+961'),
    CountryModel(name: 'Lesotho', code: 'LS', dialCode: '+266'),
    CountryModel(name: 'Liberia', code: 'LR', dialCode: '+231'),
    CountryModel(name: 'Libya', code: 'LY', dialCode: '+218'),
    CountryModel(name: 'Liechtenstein', code: 'LI', dialCode: '+423'),
    CountryModel(name: 'Lithuania', code: 'LT', dialCode: '+370'),
    CountryModel(name: 'Luxembourg', code: 'LU', dialCode: '+352'),
    CountryModel(name: 'Macao', code: 'MO', dialCode: '+853'),
    CountryModel(name: 'Madagascar', code: 'MG', dialCode: '+261'),
    CountryModel(name: 'Malawi', code: 'MW', dialCode: '+265'),
    CountryModel(name: 'Malaysia', code: 'MY', dialCode: '+60'),
    CountryModel(name: 'Maldives', code: 'MV', dialCode: '+960'),
    CountryModel(name: 'Mali', code: 'ML', dialCode: '+223'),
    CountryModel(name: 'Malta', code: 'MT', dialCode: '+356'),
    CountryModel(name: 'Marshall Islands', code: 'MH', dialCode: '+692'),
    CountryModel(name: 'Martinique', code: 'MQ', dialCode: '+596'),
    CountryModel(name: 'Mauritania', code: 'MR', dialCode: '+222'),
    CountryModel(name: 'Mauritius', code: 'MU', dialCode: '+230'),
    CountryModel(name: 'Mayotte', code: 'YT', dialCode: '+262'),
    CountryModel(name: 'Mexico', code: 'MX', dialCode: '+52'),
    CountryModel(name: 'Monaco', code: 'MC', dialCode: '+377'),
    CountryModel(name: 'Mongolia', code: 'MN', dialCode: '+976'),
    CountryModel(name: 'Montenegro', code: 'ME', dialCode: '+382'),
    CountryModel(name: 'Montserrat', code: 'MS', dialCode: '+1664'),
    CountryModel(name: 'Morocco', code: 'MA', dialCode: '+212'),
    CountryModel(name: 'Mozambique', code: 'MZ', dialCode: '+258'),
    CountryModel(name: 'Myanmar', code: 'MM', dialCode: '+95'),
    CountryModel(name: 'Namibia', code: 'NA', dialCode: '+264'),
    CountryModel(name: 'Nauru', code: 'NR', dialCode: '+674'),
    CountryModel(name: 'Nepal', code: 'NP', dialCode: '+977'),
    CountryModel(name: 'Netherlands', code: 'NL', dialCode: '+31'),
    CountryModel(name: 'New Caledonia', code: 'NC', dialCode: '+687'),
    CountryModel(name: 'New Zealand', code: 'NZ', dialCode: '+64'),
    CountryModel(name: 'Nicaragua', code: 'NI', dialCode: '+505'),
    CountryModel(name: 'Niger', code: 'NE', dialCode: '+227'),
    CountryModel(name: 'Nigeria', code: 'NG', dialCode: '+234'),
    CountryModel(name: 'Niue', code: 'NU', dialCode: '+683'),
    CountryModel(name: 'Norfolk Island', code: 'NF', dialCode: '+672'),
    CountryModel(name: 'North Korea', code: 'KP', dialCode: '+850'),
    CountryModel(name: 'Northern Mariana Islands', code: 'MP', dialCode: '+1670'),
    CountryModel(name: 'Norway', code: 'NO', dialCode: '+47'),
    CountryModel(name: 'Oman', code: 'OM', dialCode: '+968'),
    CountryModel(name: 'Pakistan', code: 'PK', dialCode: '+92'),
    CountryModel(name: 'Palau', code: 'PW', dialCode: '+680'),
    CountryModel(name: 'Palestine', code: 'PS', dialCode: '+970'),
    CountryModel(name: 'Panama', code: 'PA', dialCode: '+507'),
    CountryModel(name: 'Papua New Guinea', code: 'PG', dialCode: '+675'),
    CountryModel(name: 'Paraguay', code: 'PY', dialCode: '+595'),
    CountryModel(name: 'Peru', code: 'PE', dialCode: '+51'),
    CountryModel(name: 'Philippines', code: 'PH', dialCode: '+63'),
    CountryModel(name: 'Poland', code: 'PL', dialCode: '+48'),
    CountryModel(name: 'Portugal', code: 'PT', dialCode: '+351'),
    CountryModel(name: 'Puerto Rico', code: 'PR', dialCode: '+1939'),
    CountryModel(name: 'Qatar', code: 'QA', dialCode: '+974'),
    CountryModel(name: 'Romania', code: 'RO', dialCode: '+40'),
    CountryModel(name: 'Russia', code: 'RU', dialCode: '+7'),
    CountryModel(name: 'Rwanda', code: 'RW', dialCode: '+250'),
    CountryModel(name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1869'),
    CountryModel(name: 'Saint Lucia', code: 'LC', dialCode: '+1758'),
    CountryModel(name: 'Saint Vincent', code: 'VC', dialCode: '+1784'),
    CountryModel(name: 'Samoa', code: 'WS', dialCode: '+685'),
    CountryModel(name: 'San Marino', code: 'SM', dialCode: '+378'),
    CountryModel(name: 'Saudi Arabia', code: 'SA', dialCode: '+966'),
    CountryModel(name: 'Senegal', code: 'SN', dialCode: '+221'),
    CountryModel(name: 'Serbia', code: 'RS', dialCode: '+381'),
    CountryModel(name: 'Seychelles', code: 'SC', dialCode: '+248'),
    CountryModel(name: 'Sierra Leone', code: 'SL', dialCode: '+232'),
    CountryModel(name: 'Singapore', code: 'SG', dialCode: '+65'),
    CountryModel(name: 'Slovakia', code: 'SK', dialCode: '+421'),
    CountryModel(name: 'Slovenia', code: 'SI', dialCode: '+386'),
    CountryModel(name: 'Solomon Islands', code: 'SB', dialCode: '+677'),
    CountryModel(name: 'Somalia', code: 'SO', dialCode: '+252'),
    CountryModel(name: 'South Africa', code: 'ZA', dialCode: '+27'),
    CountryModel(name: 'South Korea', code: 'KR', dialCode: '+82'),
    CountryModel(name: 'South Sudan', code: 'SS', dialCode: '+211'),
    CountryModel(name: 'Spain', code: 'ES', dialCode: '+34'),
    CountryModel(name: 'Sri Lanka', code: 'LK', dialCode: '+94'),
    CountryModel(name: 'Sudan', code: 'SD', dialCode: '+249'),
    CountryModel(name: 'Suriname', code: 'SR', dialCode: '+597'),
    CountryModel(name: 'Swaziland', code: 'SZ', dialCode: '+268'),
    CountryModel(name: 'Sweden', code: 'SE', dialCode: '+46'),
    CountryModel(name: 'Switzerland', code: 'CH', dialCode: '+41'),
    CountryModel(name: 'Syria', code: 'SY', dialCode: '+963'),
    CountryModel(name: 'Taiwan', code: 'TW', dialCode: '+886'),
    CountryModel(name: 'Tajikistan', code: 'TJ', dialCode: '+992'),
    CountryModel(name: 'Tanzania', code: 'TZ', dialCode: '+255'),
    CountryModel(name: 'Thailand', code: 'TH', dialCode: '+66'),
    CountryModel(name: 'Timor-Leste', code: 'TL', dialCode: '+670'),
    CountryModel(name: 'Togo', code: 'TG', dialCode: '+228'),
    CountryModel(name: 'Tonga', code: 'TO', dialCode: '+676'),
    CountryModel(name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1868'),
    CountryModel(name: 'Tunisia', code: 'TN', dialCode: '+216'),
    CountryModel(name: 'Turkey', code: 'TR', dialCode: '+90'),
    CountryModel(name: 'Turkmenistan', code: 'TM', dialCode: '+993'),
    CountryModel(name: 'Turks and Caicos Islands', code: 'TC', dialCode: '+1649'),
    CountryModel(name: 'Tuvalu', code: 'TV', dialCode: '+688'),
    CountryModel(name: 'Uganda', code: 'UG', dialCode: '+256'),
    CountryModel(name: 'Ukraine', code: 'UA', dialCode: '+380'),
    CountryModel(name: 'United Arab Emirates', code: 'AE', dialCode: '+971'),
    CountryModel(name: 'United Kingdom', code: 'GB', dialCode: '+44'),
    CountryModel(name: 'United States', code: 'US', dialCode: '+1'),
    CountryModel(name: 'Uruguay', code: 'UY', dialCode: '+598'),
    CountryModel(name: 'Uzbekistan', code: 'UZ', dialCode: '+998'),
    CountryModel(name: 'Vanuatu', code: 'VU', dialCode: '+678'),
    CountryModel(name: 'Vatican City', code: 'VA', dialCode: '+379'),
    CountryModel(name: 'Venezuela', code: 'VE', dialCode: '+58'),
    CountryModel(name: 'Vietnam', code: 'VN', dialCode: '+84'),
    CountryModel(name: 'Virgin Islands, British', code: 'VG', dialCode: '+1284'),
    CountryModel(name: 'Virgin Islands, U.S.', code: 'VI', dialCode: '+1340'),
    CountryModel(name: 'Wallis and Futuna', code: 'WF', dialCode: '+681'),
    CountryModel(name: 'Yemen', code: 'YE', dialCode: '+967'),
    CountryModel(name: 'Zambia', code: 'ZM', dialCode: '+260'),
    CountryModel(name: 'Zimbabwe', code: 'ZW', dialCode: '+263'),
  ];

  static List<dynamic>? validatePhoneNumber(String phoneNumber) {
    for (final country in all) {
      if (phoneNumber.startsWith(country.dialCode)) {
        final numberWithoutCode = phoneNumber.substring(country.dialCode.length);
        return [country, numberWithoutCode, country.code, country.dialCode];
      }
    }
    return null;
  }
}
